configfile: "config/config.yaml"

rule download_llm:
    output:
        directory("resources/models/{model_name}")
    shell:
        r"""
            workflow/scripts/save_pretrained.py {wildcards.model_name} {output}
        """

rule embed:
    input:
        model_dir="resources/models/{model_name}",
        input_dir="resources/stimuli"
    output:
        directory("results/embeddings/{model_name}")
    shell:
        r"""
            python workflow/scripts/embed.py \
                --model-path {input.model_dir} \
                --input-dir {input.input_dir}
        """