configfile: "config/config.yaml"

MODEL_KEYS = list(config["models"].keys())

rule all:
    input:
        expand(
            "results/{model}_embeddings.parquet",
            model=MODEL_KEYS
        )

rule download_pretrained_llm:
    output:
        model_dir=directory("resources/models/{model}")
    params:
        hf_name=lambda wc: config["models"][wc.model]["hf_name"]
    conda:
        "envs/download_pretrained_llm_environment.yaml"
    shell:
        r"""
            python3 workflow/scripts/download_pretrained_llm.py {params.hf_name:q} {output.model_dir:q}
        """

rule get_embeddings:
    input:
        model_dir="resources/models/{model}",
        input_dir="resources/stimuli"
    output:
        embedding_dataframe="results/{model}_embeddings.parquet"
    params:
        quantization_method=config["quantization_method"],
        excluded_stimuli=" ".join(config["schema_subtasks"])
    conda:
        "envs/get_embeddings_environment.yaml"
    shell:
        r"""
            python3 workflow/scripts/get_embeddings.py \
                --input_dir {input.input_dir:q} \
                --output {output.embedding_dataframe:q} \
                --model_path {input.model_dir:q} \
                --quantization_method {params.quantization_method} \
                --excluded_stimuli {params.excluded_stimuli}
        """