# models name
models:
  bloom_560m:
    name: "BLOOMZ-560M"
    hf_name: "bigscience/bloomz-560m"
    quantization_method: null
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/bigscience_bloomz-560m_pool-avg.pt"
  bloom_1b1:
    name: "BLOOMZ-1.1B"
    hf_name: "bigscience/bloomz-1b1"
    quantization_method: null
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/bigscience_bloomz-1b1_pool-avg.pt"
  bloom_1b7:
    name: "BLOOMZ-1.7B"
    hf_name: "bigscience/bloomz-1b7"
    quantization_method: null
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/bigscience_bloomz-1b7_pool-avg.pt"
  bloom_3b:
    name: "BLOOMZ-3B"
    hf_name: "bigscience/bloomz-3b"
    quantization_method: null
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/bigscience_bloomz-3b_pool-avg.pt"
  bloom_7b1:
    name: "BLOOMZ-7.1B"
    hf_name: "bigscience/bloomz-7b1"
    # use "4bit" or "8bit" if batch size / hidden-state extraction causes OOM
    quantization_method: null
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/bigscience_bloomz-7b1_pool-avg.pt"
  openllama_3b:
    name: "OpenLLaMA-3B"
    hf_name: "openlm-research/open_llama_3b"
    quantization_method: null
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/openlm-research_open_llama_3b_pool-avg.pt"
  openllama_7b:
    name: "OpenLLaMA-7B"
    hf_name: "openlm-research/open_llama_7b"
    quantization_method: null
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/openlm-research_open_llama_7b_pool-avg.pt"
  openllama_13b:
    name: "OpenLLaMA-13B"
    hf_name: "openlm-research/open_llama_13b"
    # use "4bit" only if 8bit still gives OOM
    quantization_method: "8bit"
#    url: "http://vision14.csail.mit.edu/prh/wit_1024/openlm-research_open_llama_13b_pool-avg.pt"

# number of nearest neighbours to compute for each stimulus and model
number_of_neighbours: 5

# subtasks of "schema" task
schema_subtasks:
  - "bigbang"
  - "friends"
  - "himym"
  - "santa"
  - "seinfeld"
  - "shame"
  - "upintheair"
  - "vinny"